packages:
  - 'apps/*'
  - 'tools/*'
  - 'packages/*'
  - 'packages/channels/*'
  - 'snippets/*'
allowBuilds:
  bcrypt: true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
  sharp: true

catalog:
  '@biomejs/biome': '2.4.13'
  '@types/node': '24.10.4'
  oxlint: '1.62.0'
  typescript: '6.0.3'

minimumReleaseAge: 20160
minimumReleaseAgeExclude: []

packageExtensions:
  bcrypt:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  better-sqlite3:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
  sharp:
    dependencies:
      node-addon-api: '*'
      node-gyp: '*'
