#!/usr/bin/env tsx
/**
 * Display resolved configuration
 *
 * Usage: pnpm config:show
 *
 * Shows all configuration values with secrets redacted.
 * Useful for debugging configuration issues.
 */

// Load environment first
import "../lib/env-loader.js";

import { config, getConfigSummary } from "../config/index.js";

console.log("");
console.log("Eclaire Configuration");
console.log("=====================");
console.log("");

const summary = getConfigSummary(config);

// Group and display config
console.log("Runtime Context:");
console.log(`  runtime:        ${config.runtime}`);
console.log(`  home:           ${config.home}`);
console.log(`  nodeEnv:        ${config.nodeEnv}`);
console.log(`  isProduction:   ${config.isProduction}`);
console.log(`  isContainer:    ${config.isContainer}`);
console.log("");

console.log("Server:");
console.log(`  port:           ${config.port}`);
console.log(`  host:           ${config.host}`);
console.log(`  logLevel:       ${config.logLevel}`);
console.log("");

console.log("Service:");
console.log(`  serviceRole:    ${config.serviceRole}`);
console.log(`  databaseType:   ${config.databaseType}`);
console.log(`  queueBackend:   ${config.queueBackend}`);
console.log("");

console.log("Database:");
console.log(`  type:           ${config.database.type}`);
console.log(`  host:           ${config.database.host}`);
console.log(`  port:           ${config.database.port}`);
console.log(`  name:           ${config.database.name}`);
if (config.database.type === "sqlite") {
  console.log(`  sqlitePath:     ${config.database.sqlitePath}`);
}
if (config.database.type === "pglite") {
  console.log(`  pgliteDir:      ${config.database.pgliteDir}`);
}
console.log("");

console.log("Queue:");
console.log(`  backend:        ${config.queue.backend}`);
if (config.queue.backend === "redis") {
  console.log(`  redisUrl:       ${config.queue.redisUrl}`);
}
console.log("");

console.log("Directories:");
console.log(`  data:           ${config.dirs.data}`);
console.log(`  config:         ${config.dirs.config}`);
console.log(`  users:          ${config.dirs.users}`);
console.log(`  logs:           ${config.dirs.logs}`);
console.log(`  browserData:    ${config.dirs.browserData}`);
console.log("");

console.log("AI Providers:");
console.log(`  localUrl:       ${config.ai.localProviderUrl}`);
console.log(`  workerLocalUrl: ${config.ai.workerLocalProviderUrl}`);
if (config.ai.proxyProviderUrl) {
  console.log(`  proxyUrl:       ${config.ai.proxyProviderUrl}`);
}
console.log(`  timeout:        ${config.ai.timeout}ms`);
console.log("");

console.log("Services:");
console.log(`  docling:        ${config.services.doclingUrl}`);
console.log(`  frontend:       ${config.services.frontendUrl}`);
console.log(`  backend:        ${config.services.backendUrl}`);
console.log("");

console.log("Worker:");
console.log(`  port:           ${config.worker.port}`);
console.log(`  concurrency:    ${config.worker.concurrency}`);
console.log("");

console.log("Security:");
console.log(`  secrets:        ${config.security.secretsAutoGenerated ? "[AUTO-GENERATED]" : "[CONFIGURED]"}`);
console.log("");

// Check for potential issues
const warnings: string[] = [];

if (config.security.secretsAutoGenerated) {
  warnings.push("Using auto-generated secrets (sessions won't persist across restarts)");
  warnings.push("Run 'pnpm setup:dev' to generate persistent secrets");
}

if (warnings.length > 0) {
  console.log("Warnings:");
  for (const warning of warnings) {
    console.log(`  ⚠️  ${warning}`);
  }
  console.log("");
}
